FROM golang:1.24.4-bookworm@sha256:2b85dcbf57258bceaa4599bc29efd92824b19b5f9a93b373b9df0856b8127cba as build

WORKDIR /trillian

ARG GOFLAGS=""
ENV GOFLAGS=$GOFLAGS

# Set up access to private modules using SSH
RUN mkdir -p -m 0700 /root/.ssh && \
    ssh-keyscan github.com > /root/.ssh/known_hosts && \
    git config --global url."git@github.com:".insteadOf "https://github.com/"

ENV GOPRIVATE=github.com/digicert/ctutils
ENV GOSUMDB=off

# Download dependencies first - this should be cacheable.
COPY go.mod go.sum ./
# Mount SSH agent socket during build and enable verbose output
RUN --mount=type=ssh GODEBUG=httptrace=1 go mod download -x

# Now add the local Trillian repo, which typically isn't cacheable.
COPY . .

# Build the server.
RUN go install ./cmd/trillian_log_server
# Run the licensing tool and save licenses, copyright notices, etc.
RUN go run github.com/google/go-licenses/v2 save ./cmd/trillian_log_server --save_path /THIRD_PARTY_NOTICES

# Make a minimal image.
FROM gcr.io/distroless/base-debian12@sha256:201ef9125ff3f55fda8e0697eff0b3ce9078366503ef066653635a3ac3ed9c26

COPY --from=build /go/bin/trillian_log_server /
COPY --from=build /THIRD_PARTY_NOTICES /THIRD_PARTY_NOTICES

ENTRYPOINT ["/trillian_log_server"]
