name: govulncheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CT_APP_ID }}
          private-key: ${{ secrets.CT_APP_PRIVATE_KEY }}
          owner: digicert
          repositories: ctutils

      - name: Authenticate with private ctutils
        run: |
          git config --global url."https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/".insteadOf "https://github.com/"

      - id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        env:
          GOPRIVATE: github.com/digicert/ctutils
          GONOSUMDB: github.com/digicert/ctutils
        with:
          go-version-file: go.mod
          go-package: ./...
